# Repo: MySpace/TemplateRepo

# File: azure-pipeline.yml
name: cicd_ci

trigger:
  branches:
    include:
      - master

stages:
- stage: CI_Checks
  jobs:
  - job:
  displayName: yamllint_checks
    pool:
      vmImage: 'ubuntu-latest'
    steps:
task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"